# site
title: Russel Neiss
baseurl: "/"
url: "http://rneiss.github.io"
favicon: "/assets/sample/ico.png"
#g_analytics:

# bio
header: Russel Neiss
desc: >
  I build creative digital experiences, (usually with a Jewish flavor).

# posts
date_format: "%Y"
post_title: Project Name
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
